FROM python:3.10-slim

WORKDIR /app

# --- FIX LightGBM ---
RUN apt-get update && apt-get install -y --no-install-recommends \
  libgomp1 && \
  rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app /app/app
COPY ./artifacts /app/artifacts

CMD ["python", "-m", "app.worker"]
